-- phpMyAdmin SQL Dump
-- version 3.2.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Feb 18, 2019 at 10:26 AM
-- Server version: 5.1.41
-- PHP Version: 5.3.1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `web-lirik`
--

-- --------------------------------------------------------

--
-- Table structure for table `kategori`
--

CREATE TABLE IF NOT EXISTS `kategori` (
  `kid` int(11) NOT NULL AUTO_INCREMENT,
  `kategori` varchar(30) NOT NULL,
  PRIMARY KEY (`kid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=13 ;

--
-- Dumping data for table `kategori`
--

INSERT INTO `kategori` (`kid`, `kategori`) VALUES
(1, 'Pop Indonesia'),
(2, 'Pop Barat'),
(11, 'Rock Barat');

-- --------------------------------------------------------

--
-- Table structure for table `lirik`
--

CREATE TABLE IF NOT EXISTS `lirik` (
  `lid` int(11) NOT NULL AUTO_INCREMENT,
  `kid` int(11) NOT NULL,
  `artis` varchar(50) NOT NULL,
  `judul` varchar(100) NOT NULL,
  `lirik` text NOT NULL,
  `dibuat` int(11) NOT NULL,
  `diubah` int(11) NOT NULL,
  `dilihat` int(11) NOT NULL,
  PRIMARY KEY (`lid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=31 ;

--
-- Dumping data for table `lirik`
--

INSERT INTO `lirik` (`lid`, `kid`, `artis`, `judul`, `lirik`, `dibuat`, `diubah`, `dilihat`) VALUES
(20, 11, 'U2', 'Surrender', 'Oh, the city is alight\r\nWith lovers and lies\r\nBright blue eyes\r\nOh, the city is bright\r\nIt is brighter than day tonight\r\n\r\nSurrender, surrender\r\nSurrender, surrender\r\n\r\nSadie said she could not work out\r\nWhat it was all about\r\nAnd so she let go\r\nNow Sadie is on the street\r\nAnd the people she meets you know\r\nShe tried to be a good girl and a good wife\r\nRaise a good family\r\nLead a good life\r\nIt is not good enough\r\nShe got herself up on the forty-eighth floor\r\nGotta find out\r\nFind out what she is living for\r\n\r\nSurrender, surrender\r\nSurrender, surrender\r\n\r\nTonight\r\n\r\nOh, the city is afire\r\nA passionate flame\r\nIt knows me by name\r\nOh, the city is desire\r\nTo take me for more and more\r\nIt is in the street, getting under my feet\r\nIt is in the air, it is everywhere\r\nMy love for you\r\nIt is in the things I do and say\r\nAnd if I want to live I gotta\r\nDie to myself someday\r\n\r\nPapa sing my sing my sing my song\r\nPapa sing my sing my sing my song\r\nPapa sing my sing my sing my song\r\n\r\nSurrender, surrender\r\nSurrender, surrender', 1550474422, 1550474422, 0),
(21, 11, 'U2', 'A Day Without Me', 'Starting a landslide in my ego\r\nLook from the outside\r\nTo the world I left behind\r\n\r\nI m dreaming\r\nYou re awake\r\nIf I were sleeping\r\nWhat is at stake\r\nA day without me\r\n\r\nWhatever the feelings\r\nI keep feeling\r\nWhat are the feelings\r\nYou left behind\r\n\r\nToday s a day without me\r\n\r\nI started a landslide in my ego\r\nLook from the outside\r\nTo the world I left behind\r\n\r\nIn the world I left behind\r\nWipe their eyes, and then let go\r\nTo the world I left behind\r\nShed a tear, and then let go', 1548697418, 1548697418, 0),
(3, 1, 'Project Pop', 'Move On', 'bikin orang bloon\r\nOooo we?re gonna move on tonight lets have fun we gonna party\r\nOooo we?re gonna move on bapak ibu semua ayo kita kemon\r\nOooo we?re gonna move on tonight lets have fun we?re gonna party\r\n\r\nYo yo check it out hati galau galau galau galau harus disetop\r\nCaranya gak repo repot yo party bareng project pop\r\nHey you know jadi woles mata banyak nangis bikin males\r\nMuka jelek ouw what a mess lets party baby pasti beres\r\n\r\nAku takkan jadi butiran debu uu..\r\nJika tersesat kehilangan arah aku kan bisa bertanya\r\n\r\nOooo we?re gonna move on hati galau hanya bikin orang bloon\r\nOooo we?re gonna move on tonight lets have fun we gonna party\r\nOooo we?re gonna move on bapak ibu semua ayo kita kemon\r\nOooo we?re gonna move on tonight lets have fun we?re gonna party\r\nOooo we?re gonna party\r\n\r\nOooo we?re gonna move on hati galau hanya bikin orang bloon\r\nOooo we?re gonna move on tonight lets have fun we gonna party\r\nOooo we?re gonna move on bapak ibu semua ayo kita kemon\r\nOooo we?re gonna move on tonight lets have fun we?re gonna party ', 1550474422, 1550474422, 7),
(22, 11, 'U2', 'Party Girl', 'I know a girl, a girl called Party\r\nParty girl\r\nI know she wants more than a party\r\nParty girl\r\nAnd she wont tell me her name\r\nOh no, not me\r\n\r\nI know a boy, a boy called Trash\r\nTrash Can\r\nI know he does all that he can\r\nWham-Bam\r\nAnd she wont tell me his name\r\nOh no, not me\r\n\r\nWhen I was three, I thought the world revolved around me, I was wrong\r\nAnd so I sing along\r\nAnd if you dance, then dance with me\r\n\r\nI know a girl, a girl called Party\r\nParty girl\r\nI know she wants more than a party\r\nParty girl\r\nI know a boy, a boy called Trampoline\r\nYou know what I mean\r\n\r\nI think I know what he wants\r\nI think I know what he wants\r\nI think I know what you want\r\nI think I know what you want\r\nI think I know what you want\r\nI think I know what you want\r\nI think I know what he wants', 1550474422, 1550474422, 0),
(23, 11, 'Handwritten', 'Handwritten', 'Pull it out, turn it up, what is your favorite song?\r\nThat is mine, I have been crying to it since I was young\r\nI know there is someone out there feeling just like I feel\r\nI know they are waiting up, I know they are waiting to heal\r\nAnd I have been holding my breath\r\nAre you holding your breath\r\nFor too many years to count?\r\nToo many years to count\r\n\r\nAnd we waited for the sirens that never come\r\nAnd we only write by the moon\r\nEvery word handwritten\r\nAnd to ease the loss of youth\r\nAnd how many years I have missed you\r\nPages plead forgiveness\r\nEvery word handwritten\r\n\r\nLet it out, let me in, take a hold of my hand\r\nThere is nothing like another soul that is been cut up the same\r\nAnd did you want to drive without a word in between?\r\nI can understand, you need a minute to breathe\r\nAnd to sew up the seams after all this defeat\r\nAll this defeat\r\n\r\nAnd we waited for the sirens that never come\r\nAnd we only write by the moon\r\nEvery word handwritten\r\nAnd to ease the loss of youth\r\nAnd the many, many years I have missed you\r\nPages plead forgiveness\r\nEvery word handwritten\r\n\r\nHere in the dark, I cherish the moonlight\r\nI am in love with the way you are in love with the night\r\nAnd it travels from heart to limb to pen\r\n\r\nAnd we waited for the sirens that never come\r\nAnd we only write by the moon\r\nEvery word handwritten\r\nEvery word handwritten\r\n\r\nAnd with this pen, I thee wed\r\nFrom my heart to your distress\r\n\r\nEvery word handwritten', 1550474422, 1550474422, 1),
(8, 2, 'Avril Lavigne', 'Girl Friend', '[Chorus]\r\nHey! Hey! You! You!\r\nI don;t like your girlfriend!\r\nNo way! No way!\r\nI think you need a new one\r\nHey! Hey! You! You!\r\nI could be your girlfriend\r\nHey! Hey! You! You!\r\nI know that you like me\r\nNo way! No way!\r\nI know it''s not a secret\r\nHey! Hey! You! You!\r\nI want to be your girlfriend\r\n\r\n[Verse 1]\r\nYou''re so fine\r\nI want you mine\r\nYou''re so delicious\r\nI think about you all the time\r\nYou''re so addictive\r\nDon''t you know what I could do to make you feel alright (alright, alright, alright)?\r\nDon''t pretend I think you know I''m damn precious\r\nAnd Hell Yeah\r\nI''m the motherfucking princess\r\nI can tell you like me too and you know I''m right\r\n\r\n[Bridge:]\r\nShe''s like so whatever\r\nYou could do so much better\r\nI think we should get together now\r\nAnd that''s what everyone''s talking about!\r\n\r\n[Chorus:]\r\nHey! Hey! You! You!\r\nI don''t like your girlfriend!\r\nNo way! No way!\r\nI think you need a new one\r\nHey! Hey! You! You!\r\nI could be your girlfriend\r\nHey! Hey! You! You!\r\nI know that you like me\r\nNo way! No way!\r\nYou know it''s not a secret\r\nHey! Hey! You! You!\r\nI want to be your girlfriend\r\n\r\n[Verse 2]\r\nI can see the way, I see the way you look at me\r\nAnd even when you look away I know you think of me\r\nI know you talk about me all the time again and again (again, again, again)\r\nSo come over here, tell me what I want to hear\r\nBetter yet make your girlfriend disappear\r\nI don''t want to hear you say her name ever again (and again, and again, and again!)\r\n\r\n[Bridge]\r\n\r\n[Chorus]\r\nHey! Hey! You! You!\r\nI don''t like your girlfriend!\r\nNo way! No way!\r\nI think you need a new one\r\nHey! Hey! You! You!\r\nI could be your girlfriend\r\nHey! Hey! You! You!\r\nI know that you like me\r\nNo way! No way!\r\nYou know it''s not a secret\r\nHey! Hey! You! You!\r\nI want to be your girlfriend\r\n\r\nIn a second you''ll be wrapped around my finger\r\n''cause I can, ''cause I can do it better\r\nThere''s no other\r\nSo when''s it gonna sink in?\r\nShe''s so stupid\r\nWhat the hell were you thinking?!\r\n[repeat]\r\n\r\n[Chorus x2]\r\nHey! Hey! You! You!\r\nI don''t like your girlfriend!\r\nNo way! No way!\r\nI think you need a new one\r\nHey! Hey! You! You!\r\nI could be your girlfriend\r\nNo way! No way!\r\nHey! Hey! You! You!\r\nI know that you like me\r\nNo way! No way!\r\nYou know it''s not a secret\r\nHey! Hey! You! You!\r\nI want to be your girlfriend\r\nNo way! No way!\r\n\r\nHey! Hey!', 1550474422, 1550474422, 37),
(9, 2, 'Bruno Mars', 'Grenade', 'Reff:\r\nI?d catch a grenade for you (yeah, yeah, yeah)\r\nThrow my hand on a blade for you (yeah, yeah, yeah)\r\nI?d jump in front of a train for you (yeah, yeah, yeah)\r\nYou know I?d do anything for you (yeah, yeah, yeah)\r\nOh, I would go through all this pain\r\nTake a bullet straight through my brain\r\nYes, I would die for you, baby\r\nBut you won?t do the same\r\n\r\nNo, no, no, no\r\n\r\nBlack, black, black and blue\r\nBeat me ?til I?m numb\r\nTell the devil I said ?Hey? when you get back to where you?re from\r\nMad woman, bad woman\r\nThat?s just what you are\r\nYeah, you smile in my face then rip the brakes out my car\r\n\r\nGave you all I had\r\nAnd you tossed it in the trash\r\nYou tossed it in the trash, yes you did\r\nTo give me all your love is all I ever asked\r\n?Cause what you don?t understand is?\r\n\r\nReff:\r\nI?d catch a grenade for you (yeah, yeah, yeah)\r\nThrow my hand on the blade for you (yeah, yeah, yeah)\r\nI?d jump in front of a train for you (yeah, yeah, yeah)\r\nYou know I?d do anything for you (yeah, yeah, yeah)\r\nOh, I would go through all this pain\r\nTake a bullet straight through my brain\r\nYes, I would die for you, baby\r\nBut you won?t do the same\r\n\r\nIf my body was on fire\r\nOh, you would watch me burn down in flames\r\nYou said you loved me, you?re a liar\r\n?Cause you never ever ever did, baby\r\n\r\nReff:\r\nBut, darling, I?d still catch a grenade for you (yeah, yeah, yeah)\r\nThrow my hand on the blade for you (yeah, yeah, yeah)\r\nI?d jump in front of a train for you (yeah, yeah, yeah)\r\nYou know I?d do anything for you (yeah, yeah, yeah)\r\nOh, I would go through all this pain\r\nTake a bullet straight through my brain\r\nYes, I would die for you, baby\r\nBut you won?t do the same\r\n\r\nNo, you won?t do the same\r\nYou wouldn?t do the same\r\nOh, you?d never do the same\r\nOh, no no no', 1550474453, 1550474453, 11),
(10, 2, 'Avril Lavigne', 'Complicated', 'Uh huh, life''s like this\r\nUh huh, uh huh, that''s the way it is\r\nCause life''s like this\r\nUh huh, uh huh that''s the way it is\r\n\r\nChill out whatcha yelling'' for?\r\nLaid back it''s all been done before\r\nAnd if you could only let it be\r\nyou will see\r\nI like you the way you are\r\nWhen we''re drivin'' in your car\r\nand you''re talking to me one on one but you''ve become\r\n\r\nSomebody else round everyone else\r\nYou''re watching your back like you can''t relax\r\nYou''re tryin'' to be cool you look like a fool to me\r\nTell me\r\n\r\nWhy do you have to go and make things so complicated?\r\nI see the way you''re acting like you''re somebody else gets me frustrated\r\nLife''s like this you\r\nAnd you fall and you crawl and you break\r\nand you take what you get and you turn it into honesty\r\nand promise me I''m never gonna find you fake it\r\nno no no\r\n\r\nYou come over unannounced\r\ndressed up like you''re somethin'' else\r\nwhere you are ain''t where it''s at you see\r\nyou''re making me\r\nlaugh out when you strike your pose\r\ntake off all your preppy clothes\r\nyou know you''re not fooling anyone\r\nwhen you''ve become\r\n\r\nSomebody else round everyone else\r\nWatching your back, like you can''t relax\r\nTrying to be cool you look like a fool to me\r\nTell me\r\n\r\nWhy do you have to go and make things so complicated?\r\nI see the way you''re acting like you''re somebody else gets me frustrated\r\nLife''s like this you\r\nand You fall and you crawl and you break\r\nand you take what you get and you turn it into\r\nhonesty\r\npromise me I''m never gonna find you fake it\r\nno no no\r\n\r\nChill out whatcha yelling for?\r\nLay back, it''s all been done before\r\nAnd if you could only let it be\r\nYou will see\r\n\r\nSomebody else round everyone else\r\nYou''re watching your back, like you can''t relax\r\nYou''re trying to be cool, you look like a fool to me\r\nTell me\r\n\r\nWhy do you have to go and make things so complicated?\r\nI see the way you''re acting like you''re somebody else gets me frustrated\r\nLife''s like this you\r\nand you fall and you crawl and you break\r\nand you take what you get and you turn it into\r\nhonesty\r\npromise me I''m never gonna find you fake it\r\nno no no\r\n\r\nWhy do you have to go and make things so complicated?\r\nI see the way you''re acting like your somebody else gets me frustrated\r\nLife''s like this you\r\nYou fall and you crawl and you break\r\nand you take what you get and you turn it into honesty\r\npromise me I''m never gonna find you fake it\r\nno no no', 1550474422, 1550474422, 9),
(11, 1, 'Cherry Belle', 'I''ll Be There For You', 'Sedihnya diriku merindukanmu..rindukanmu\r\nKatakan padaku arti diriku?dihatimu..\r\nKu kan ada ..untukmu..\r\nKau selalu ..dihatiku..\r\n\r\nEverytime you miss me..you need me..\r\nRemember me\r\nI will come to you i promise you i love you\r\n\r\nEverytime you miss me..you need me\r\nCall me call me\r\nI will come to you i promise you.. i?ll be there for you..\r\n\r\nSedihnya diriku merindukanmu?rindukanmu\r\nKatakan padaku arti diriku ..dihatimu..\r\nKu kan ada ..untukmu..\r\nKau selalu ..dihatiku..\r\n\r\nEverytime you miss me..you need me..\r\nRemember me\r\nI will come to you i promise you i love you\r\n\r\nEverytime you miss me..you need me..\r\nCall me call me\r\nI will come to you i promise you.. i?ll be there for you..\r\n\r\nFor you..For you..\r\n\r\nEverytime you miss me..you need me..\r\nRemember me\r\nI will come to you i promise you i love you\r\n\r\nEverytime you miss me..you need me..\r\nCall me call me\r\nI will come to you i promise you.. i?ll be there for you..\r\n\r\nEverytime you miss me..you need me..\r\nRemember me\r\nI will come to you i promise you i love you\r\n\r\nEverytime you miss me..you need me..\r\nCall me call me\r\nI will come to you i promise you.. i?ll be there for you..\r\n\r\nI?ll be there for you..', 1550474476, 1550474476, 2),
(12, 1, 'Cherry Belle', 'Dilema', 'Tuhan tolong aku\r\nKu tak dapat menahan rasa didadaku\r\nIngin aku memiliki\r\nNamun dia ada yang punya\r\n\r\nTuhan bantu aku\r\nTernyata dia kekasih sahabatku\r\nEntah apa yang harus ku katakan\r\nHatiku bimbang jadi tak menentu\r\n\r\nBukan maksud diriku melukai hatimu\r\nNamun aku juga wanita\r\nYang ingin merasakan cinta\r\n\r\nNever never want you\r\nReally really love you\r\nMaafkan aku mengecewakanmu\r\nReally really love you\r\nNever never leave you\r\nSegera aku melupakan dirinya\r\n\r\nNever never want you\r\nReally really love you\r\nMaafkan aku mengecewakanmu\r\nReally really love you\r\nNever never leave you\r\nSegera aku melupakan dirinya\r\n\r\nBukan maksud diriku melukai hatimu\r\nNamun aku juga wanita\r\nYang ingin merasa jatuh cinta\r\n\r\nNever never want you\r\nReally really love you\r\nMaafkan aku mengecewakanmu\r\nReally really love you\r\nNever never leave you\r\nSegera aku melupakan dirinya\r\n\r\nNever never want you\r\nReally really love you\r\nMaafkan aku mengecewakanmu\r\nReally really love you\r\nNever never leave you\r\nSegera aku melupakan dirinya', 1550474422, 1550474422, 2),
(13, 1, 'Cherry Belle', 'Best Friend Forever', 'Kan selalu bersama dalam suka duka\r\nBerbagi segalanya\r\n\r\nDi saat ku termenung kau datang bawa cerita\r\nDi saat ku bahagia kau jaga penuh hatiku\r\nApapun kisahku kamu ada untukku\r\nHanya kaulah sahabat sejatiku\r\n\r\nKita kan selalu bersama dalam suka duka\r\nBerbagi segalanya tak terpisahkan\r\nHanya kau yang ada di hatiku\r\n\r\nKita kan selalu bersama menggapai semua cinta\r\nDan meraih dunia walau badai menghadang tak akan kita terluka\r\nCause you are my best friend forever\r\n\r\nDi saat ku termenung kau datang bawa cerita\r\nDi saat ku bahagia kau jaga penuh hatiku\r\nApapun kisahku kamu ada untukku\r\nHanya kaulah sahabat sejatiku\r\n\r\nKita kan selalu bersama dalam suka duka\r\nBerbagi segalanya tak terpisahkan\r\nHanya kau yang ada di hatiku\r\n\r\nKita kan selalu bersama menggapai semua cinta\r\nDan meraih dunia walau badai menghadang tak akan kita terluka\r\nCause you are my best friend forever\r\n\r\nKan selalu bersama dalam suka duka\r\nBerbagi segalanya\r\n\r\nKita kan selalu bersama dalam suka duka\r\nBerbagi segalanya tak terpisahkan\r\nHanya kau yang ada di hatiku\r\n\r\nKita kan selalu bersama menggapai semua cinta\r\nDan meraih dunia walau badai menghadang tak akan kita terluka\r\nTerluka, tak akan kita terluka woo oww\r\nCause you are my best friend forever', 1550474422, 1550474422, 2),
(14, 1, 'Cherry Belle', 'Beautiful', 'Don''t cry, don''t be shy\r\nKamu cantik apa adanya\r\nSadari syukuri dirimu sempurna\r\nJangan dengarkan kata mereka\r\nDirimu indah pancarkan sinarmu\r\n\r\nYou are beautiful, beautiful, beautiful\r\nKamu cantik cantik dari hatimu\r\nYou are beautiful, beautiful, beautiful\r\nKamu cantik cantik dari hatimu\r\n\r\nDon''t cry, don''t be shy\r\nKamu cantik apa adanya\r\nSadari syukuri dirimu sempurna\r\nJangan dengarkan kata mereka\r\nDirimu indah pancarkan sinarmu wo oww\r\n\r\nYou are beautiful, beautiful, beautiful\r\nKamu cantik cantik dari hatimu\r\nYou are beautiful, beautiful, beautiful\r\nKamu cantik cantik dari hatimu\r\n\r\nTahukah dirimu berbeda istimewa\r\nKau bisa membuat mereka jatuh cinta\r\n\r\nYou are beautiful, beautiful, beautiful\r\nKamu cantik cantik dari hatimu\r\nYou are beautiful, beautiful, beautiful\r\nKamu cantik cantik dari hatimu\r\n\r\nYou are beautiful, beautiful, beautiful\r\nKamu cantik cantik dari hatimu\r\nYou are beautiful, beautiful, beautiful\r\nKamu cantik cantik dari hatimu', 1550474422, 1550474422, 1),
(24, 11, 'Handwritten', 'Blue Dahlia', 'On a hot self tree summer, steam just lies above them trees\r\nYou gotta stay inside and wait for the night and then come on over to see me\r\nAnd thereâ€™s a poetry about these streets and skips through the skin, goes right underneath\r\nAnd momma always knew I need a girl like you, to me I never believed\r\n\r\nCause Iâ€™ve been so lonely, I canâ€™t imagine not come and stay with me\r\nCause Iâ€™ve been so lonely, I canâ€™t imagine not come and stay with me\r\nWhere did you get them scars? How blue is your heart?\r\nIs it sad enough to break? She said it is sad enough to break\r\nHow long was your life?\r\nWas it cold and strange like mine? Are you man enough to lay here?\r\nShe said Iâ€™m man enough, my baby, come see about me\r\n\r\nHad a dream about you once, I can barely see your form\r\nAnd I met you between the wax and the needle and the words of my favorite song\r\nAnd your black hair was like a raven to your tanned skin over the beach\r\nAnd your back drop with your rollers and my side kick was all discrete\r\n\r\nAnd Iâ€™ve been so locked down, Iâ€™ve been long lost level on the ground\r\nWhere did you get them scars? How blue is your heart?\r\nIs it sad enough to break? She said it is sad enough to break\r\nHow long was your life?\r\nWas it cold and strange like mine? Are you man enough to lay here?\r\nShe said Iâ€™m man enough, my baby, come see about me\r\n\r\nDid it take you to the carnival to get locked up on the line?\r\nMe, I got caught up with the fortune tellers and the ladies with the sleepy eyes\r\nIt took years, my baby, just to come clean, every street light a reminder\r\nAnd all those apologies and the night was lonely next to mean\r\nEven the night was lonely next to me\r\n\r\nWhere did you get them scars? How blue is your heart?\r\nIs it sad enough to break? She said it is sad enough to break\r\nHow long was your life?\r\nWas it cold and strange like mine? Are you man enough to lay here?\r\nShe said Iâ€™m man enough, my baby, come see about me\r\n\r\nCome see about me, come see about me, come see about me, come see about me, come see about me\r\nWhenever youâ€™re lonely', 1550474422, 1550474422, 0),
(17, 2, 'The Carpenter', 'Close To You', 'Why do birds suddenly appear, every time you are near?\r\nJust like me, they long to be close to you.\r\nWhy do stars fall down from the sky, every time you walk by?\r\nJust like me, they long to be close to you.\r\n\r\nOn the day that you were born the angels got together.\r\nAnd decided to create a dream come true.\r\nSo, they sprinkled moon dust in your hair of gold\r\nAnd star-light in your eyes of blue.\r\nThat is why all the girls in town follow you all around.\r\nJust like me, they long to be close to you...\r\n\r\nOn the day that you were born the angels got together.\r\nAnd decided to create a dream come true.\r\nSo, they sprinkled moon dust in your hair of gold\r\nAnd star-light in your eyes of blue.\r\nThat is why all the girls in town follow you all around.\r\nJust like me, they long to be close to you...\r\nJust like me, they long to be close to you...', 1548696847, 1548696939, 0),
(18, 2, 'Adele', 'Someone Like You', 'I heard that you re settled down\r\nThat you found a girl and you re married now\r\nI heard that your dreams came true\r\nGuess she gave you things I didn t give to you\r\nOld friend, why are you so shy?\r\nAin t like you to hold back or hide from the light\r\n\r\nI hate to turn up out of the blue, uninvited\r\nBut I couldn t stay away, I couldn t fight it\r\nI had hoped you d see my face\r\nAnd that you d be reminded that, for me, it isn t over\r\n\r\nNever mind, I ll find someone like you\r\nI wish nothing but the best for you two\r\nDon t forget me, I beg\r\nI ll remember you said\r\nSometimes it lasts in love, but sometimes it hurts instead\r\nSometimes it lasts in love, but sometimes it hurts instead, yeah\r\n\r\nYou know how the time flies\r\nOnly yesterday was the time of our lives\r\nWe were born and raised in a summer haze\r\nBound by the surprise of our glory days\r\n\r\nI hate to turn up out of the blue, uninvited\r\nBut I couldn t stay away, I couldn t fight it\r\nI had hoped you d see my face\r\nAnd that you d be reminded that, for me, it isn t over\r\n\r\nNever mind, I ll find someone like you\r\nI wish nothing but the best for you two\r\nDon t forget me, I beg\r\nI ll remember you said\r\nSometimes it lasts in love, but sometimes it hurts instead\r\n\r\nNothing compares, no worries or cares\r\nRegrets and mistakes, they re memories made\r\nWho would have known how bittersweet this would taste?\r\n\r\nNever mind, I ll find someone like you\r\nI wish nothing but the best for you\r\nDon t forget me, I beg\r\nI ll remember you said\r\nSometimes it lasts in love, but sometimes it hurts instead\r\n\r\nNever mind, I ll find someone like you\r\nI wish nothing but the best for you two\r\nDon t forget me, I beg\r\nI ll remember you said\r\nSometimes it lasts in love, but sometimes it hurts instead\r\nSometimes it lasts in love, but sometimes it hurts instead, yeah, yeah', 1548697058, 1548697058, 2),
(19, 2, 'Westlife', 'My Love', 'An empty street\r\nAn empty house\r\nA hole inside my heart\r\nI am all alone\r\nThe rooms are getting smaller\r\nI wonder how\r\nI wonder why\r\nI wonder where they are\r\nThe days we had\r\nThe songs we sang together\r\nOh yeah\r\nAnd all my love\r\nI am holding on forever\r\nReaching for the love that seems so far\r\nSo I say a little prayer\r\nAnd hope my dreams will take me there\r\nWhere the skies are blue\r\nTo see you once again, my love\r\nOver seas from coast to coast\r\nTo find the place I love the most\r\nWhere the fields are green\r\nTo see you once again, my love\r\nI tried to read\r\nI go to work\r\nI am laughing with my friends\r\nBut I cant stop\r\nTo keep myself from hinking\r\nOh no\r\nI wonder how\r\nI wonder why\r\nI wonder where they are\r\nThe days we had\r\nThe songs we sang together\r\nOh yeah\r\nAnd all my love\r\nI am holding on forever\r\nReaching for the love that seems so far\r\nSo I say a little prayer\r\nAnd hope my dreams will take me there\r\nWhere the skies are blue\r\nTo see you once again, my love\r\nOver seas from coast to coast\r\nTo find the place I love the most\r\nWhere the fields are green\r\nTo see you once again\r\nTo hold you in my arms\r\nTo promise you my love\r\nTo tell you from my heart\r\nYou are all I am thinking of\r\nAnd reaching for the love that seems so far\r\nso I say a little prayer\r\nAnd hope my dreams will take me there\r\nWhere the skies are blue\r\nTo see you once again, my love\r\nOver seas from coast to coast\r\nTo find the place I love the most\r\nWhere the fields are green\r\nTo see you once again, my love\r\nSee you in a prayer\r\nMy sweet dreams will take me there\r\nWhere the skies are blue\r\nTo see you once again\r\nOver seas from coast to coast\r\nTo find the place I love the most\r\nWhere the fields are green\r\nTo see you once again, my love', 1548697159, 1548697159, 0),
(25, 2, 'Maroon 5', 'Girls Like You', 'Spent 24 hours\r\nI need more hours with you\r\nYou spent the weekend\r\nGetting even, ooh ooh\r\nWe spent the late nights\r\nMaking things right, between us\r\nBut now it`s all good baby\r\nRoll that Backwood baby\r\nAnd play me close\r\n`Cause girls like you\r\nRun around with guys like me\r\n`Til sundown, when I come through\r\nI need a girl like you, yeah yeah\r\nGirls like you\r\nLove fun, yeah me too\r\nWhat I want when I come through\r\nI need a girl like you, yeah yeah\r\nYeah yeah yeah\r\nYeah yeah yeah\r\nI need a girl like you, yeah yeah\r\nYeah yeah yeah\r\nYeah yeah yeah\r\nI need a girl like you, yeah yeah\r\nI spent last night\r\nOn the last flight to you\r\nTook a whole day up\r\nTrying to get way up, ooh ooh\r\nWe spent the daylight\r\nTrying to make things right between us\r\nAnd now it`s all good baby\r\nRoll that Backwood baby\r\nAnd play me close\r\n`Cause girls like you\r\nRun around with guys like me\r\n`Til sundown, when I come through\r\nI need a girl like you, yeah yeah\r\nGirls like you\r\nLove fun, yeah me too\r\nWhat I want when I come through\r\nI need a girl like you, yeah yeah\r\nYeah yeah yeah\r\nYeah yeah yeah\r\nI need a girl like you, yeah yeah\r\nYeah yeah yeah\r\nYeah yeah yeah\r\nI need a girl like you, yeah yeah\r\nI need a girl like you, yeah yeah\r\nI need a girl like you\r\nMaybe it`s 6:45\r\nMaybe I`m barely alive\r\nMaybe you`ve taken my shit for the last time, yeah\r\nMaybe I know that I`m drunk\r\nMaybe I know you`re the one\r\nMaybe I`m thinking it`s better if you drive\r\n`Cause girls like you\r\nRun around with guys like me\r\n`Til sundown, when I come through\r\nI need a girl like you, yeah yeah\r\n`Cause girls like you\r\nRun around with guys like me\r\n`Til sundown, when I come through\r\nI need a girl like you, yeah yeah\r\nGirls like you\r\nLove fun, yeah me too\r\nWhat I want when I come through\r\nI need a girl like you, yeah yeah\r\nYeah yeah yeah\r\nYeah yeah yeah\r\nI need a girl like you, yeah yeah\r\nYeah yeah yeah\r\nYeah yeah yeah\r\nI need a girl like you', 1550421577, 1550421577, 0),
(26, 2, 'Calum Scott', 'You Are The Reason', 'There goes my heart beating\r\n`Cause you are the reason\r\nI`m losing my sleep\r\nPlease come back now\r\nThere goes my mind racing\r\nAnd you are the reason\r\nThat I`m still breathing\r\nI`m hopeless now\r\nI`d climb every mountain\r\nAnd swim every ocean\r\nJust to be with you\r\nAnd fix what I`ve broken\r\nOh, `cause I need you to see\r\nThat you are the reason\r\nThere goes my hand shaking\r\nAnd you are the reason\r\nMy heart keeps bleeding\r\nI need you now\r\nIf I could turn back the clock\r\nI`d make sure the light defeated the dark\r\nI`d spend every hour, of every day\r\nKeeping you safe\r\nAnd I`d climb every mountain\r\nAnd swim every ocean\r\nJust to be with you\r\nAnd fix what I`ve broken\r\nOh, `cause I need you to see\r\nThat you are the reason, oh\r\n(I don`t wanna fight no more)\r\n(I don`t wanna hurt no more)\r\n(I don`t wanna cry no more)\r\n(Come back, I need you to hold me closer now) \r\nYou are the reason, oh\r\n(Just a little closer now) \r\n(Come a little closer now)\r\n(I need you to hold me tonight)\r\nI`d climb every mountain\r\nAnd swim every ocean\r\nJust to be with you\r\nAnd fix what I`ve broken\r\n`Cause I need you to see\r\nThat you are the reason', 1550421674, 1550421674, 0),
(27, 2, 'Zayn Malik', 'Let Me', 'Sweet baby, our sex has meaning\r\nKnow this time you`ll stay `til the morning\r\nDuvet days and vanilla ice cream\r\nMore than just one night together exclusively\r\nBaby, let me be your man\r\nSo I can love you\r\nAnd if you let me be your man\r\nThen I`ll take care of you, you\r\nFor the rest of my life, for the rest of yours\r\nFor the rest of my life, for the rest of yours\r\nFor the rest of ours\r\nWe`re drinking the finest label\r\nDirty dancing on top of the table\r\nLong walks on the beach in April (beach in April)\r\nYeah, I promise, darling, that I`ll be faithful (be faithful)\r\nBaby, let me be your man (let me be your man)\r\nSo I can love you (I can love you)\r\nAnd if you let me be your man (let me be your man)\r\nThen I`ll take care of you (I can love you)\r\nFor the rest of my life, for the rest of yours\r\nFor the rest of my life, for the rest of yours\r\nFor the rest of ours\r\nGive me your body and let me love you like I do\r\nCome a little closer and let me do those things to you\r\nThis feeling will last forever, baby, that`s the truth\r\nLet me be your man so I can love you\r\nBaby, let me be your man (let me be your man)\r\nSo I can love you (I can love you)\r\nAnd if you let me be your man (let me be your man)\r\nThen I`ll take care of you, you (I can love you)\r\nFor the rest of my life (for the rest of my life)\r\nFor the rest of yours (for the rest of yours)\r\nFor the rest of my life (for the rest of my life)\r\nFor the rest of yours (for the rest of yours)\r\nFor the rest of ours (for the rest of ours)', 1550422440, 1550422440, 0),
(28, 2, 'Joseph Vincent', 'Can`t Take My Eyes Off You', 'You`re just too good to be true\r\nI can`t take my eyes off you\r\nYou`d be like heaven to touch\r\nI wanna hold you so much\r\nAt long last love has arrived\r\nAnd I thank God I`m alive\r\nYou`re just too good to be true\r\nCan`t take my eyes off you\r\nPardon the way that I stare\r\nThere`s nothing else to compare\r\nThe sight of you leaves me weak\r\nThere are no words left to speak\r\nBut if you feel like I feel\r\nPlease let me know that is real\r\nYou`re just too good to be true\r\nI can`t take my eyes off you\r\nI need you baby\r\nAnd if it`s quite all right\r\nI need you baby\r\nTo warm the lonely nights\r\nI love you baby\r\nTrust in me when I say okay\r\nOh pretty baby\r\nDon`t let me down I pray\r\nOh pretty baby\r\nNow that I`ve found you stay\r\nAnd let me love you, oh baby\r\nLet me love you\r\nYou`re just too good to be true\r\nI can`t take my eyes off you\r\nYou`d be like heaven to touch\r\nI wanna hold you so much\r\nAt long last love has arrived\r\nAnd I thank God I`m alive\r\nYou`re just too good to be true\r\nCan`t take my eyes off of you\r\nI need you baby\r\nAnd if it`s quite all right\r\nI need you baby\r\nTo warm the lonely nights\r\nI love you baby\r\nTrust in me when I say it`s okay\r\nOh pretty baby\r\nDon`t let me down I pray\r\nOh pretty baby\r\nNow that I`ve found you stay\r\nAnd let me love you, oh baby\r\nLet me love you, oh baby\r\nI need you baby\r\nAnd if it`s quite all right\r\nI love you baby\r\nYou warm the lonely nights\r\nI need you baby\r\nTrust in me when I say it`s okay\r\nOh pretty baby\r\nDon`t let me down I pray\r\nOh pretty baby\r\nNow that I`ve found you stay\r\nAnd let me love you, oh baby\r\nLet me love you, oh baby', 1550422486, 1550422486, 0),
(29, 2, 'Selena Gomez', 'Back To You', 'Took you like a shot\r\nThought that I could chase you with a cold evening\r\nLet a couple years water down how I`m feeling about you\r\n(Feeling about you)\r\nAnd every time we talk\r\nEvery single word builds up to this moment\r\nAnd I gotta convince myself I don`t want it\r\nEven though I do (even though I do)\r\nYou could break my heart in two\r\nBut when it heals, it beats for you\r\nI know it`s forward, but it`s true\r\nI wanna hold you when I`m not supposed to\r\nWhen I`m lying close to someone else\r\nYou`re stuck in my head and I can`t get you out of it\r\nIf I could do it all again\r\nI know I`d go back to you\r\nI know I`d go back to you\r\nI know I`d go back to you\r\nWe never got it right\r\nPlaying and replaying old conversations\r\nOverthinking every word and I hate it\r\n`Cause it`s not me (`cause it`s not me)\r\nAnd what`s the point in hiding?\r\nEverybody knows we got unfinished business\r\nAnd I`ll regret it if I didn`t say\r\nThis isn`t what it could be (isn`t what it could be)\r\nYou could break my heart in two\r\nBut when it heals, it beats for you\r\nI know it`s forward, but it`s true\r\nI wanna hold you when I`m not supposed to\r\nWhen I`m lying close to someone else\r\nYou`re stuck in my head and I can`t get you out of it\r\nIf I could do it all again\r\nI know I`d go back to you\r\nI know I`d go back to you \r\nI`d go back to you\r\nI`d go back to you\r\nWhat was there wasn`t sure\r\nBut I`d go back to you\r\nI know I`d go back to you\r\nYou can break my heart in two\r\nBut when it heals, it beats for you\r\nI know it`s forward, but it`s true\r\nWon`t lie, I`d go back to you\r\nYou know, my thoughts are running loose\r\nIt`s just a thing you make me do\r\nAnd I could fight, but what`s the use?\r\nI know I`d go back to you\r\nI wanna hold you when I`m not supposed to\r\nWhen I`m lying close to someone else\r\nYou`re stuck in my head and I can`t get you out of it\r\nIf I could do it all again\r\nI know I`d go back to you\r\nI`d go back to you\r\nI`ll go back to you\r\nI know I`d go back to you\r\n(I`d go back to you, I`d go back to you)\r\nI know I`d go back to you\r\n(Go back to you, go back to you)\r\n(Go back to you, go back to you)\r\n(Go back to you, go back to you)', 1550422566, 1550422566, 0);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE IF NOT EXISTS `user` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `fullname` varchar(40) NOT NULL,
  `username` varchar(30) NOT NULL,
  `password` varchar(32) NOT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`uid`, `fullname`, `username`, `password`) VALUES
(1, 'Ardiansyah', 'ardiansyah', '25d55ad283aa400af464c76d713c07ad'),
(2, 'Administrator', 'admin', '21232f297a57a5a743894a0e4a801fc3');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
